bdaiinstitute/predicators

predicators/approaches/bridge_policy_approach.py, predicators/bridge_policies/__init__.py, predicators/bridge_policies/base_bridge_policy.py, predicators/bridge_policies/ldl_bridge_policy.py, predicators/bridge_policies/learned_ldl_bridge_policy.py, predicators/bridge_policies/oracle_bridge_policy.py, predicators/envs/cluttered_table.py, predicators/envs/exit_garage.py, predicators/ground_truth_models/__init__.py, predicators/ground_truth_models/exit_garage/options.py, predicators/ground_truth_models/painting/__init__.py, predicators/ground_truth_models/painting/ldl_bridge_policy.py, predicators/ground_truth_models/painting/painting_bridge_policy.ldl, predicators/ground_truth_models/stick_button/__init__.py, predicators/ground_truth_models/stick_button/ldl_bridge_policy.py, predicators/ground_truth_models/stick_button/stick_button_bridge_policy.ldl, predicators/main.py, predicators/nsrt_learning/segmentation.py, predicators/settings.py, predicators/structs.py, predicators/utils.py, tests/approaches/test_bridge_policy_approach.py, tests/approaches/test_oracle_approach.py, tests/bridge_policies/test_base_bridge_policy.py, tests/bridge_policies/test_oracle_bridge_policy.py, tests/envs/test_exit_garage.py, tests/test_structs.py, tests/test_utils.py
Includes a few commits to do with bridge policy stuff.
=> Update to latest master

.github/CODEOWNERS, .predicators_pylintrc, mypy.ini, predicators/ground_truth_models/spot/options.py, predicators/spot_utils/spot_utils.py
also change `CODEOWNERS` and ignore `venv`
=> fix spot leasing issue

predicators/ground_truth_models/spot/nsrts.py, predicators/ground_truth_models/spot/options.py, predicators/spot_utils/spot_utils.py
Added Object Specific Samplers for Grasp (now parameterized by dx, dy, dz of post-grasp location, and grasp type [-1 any, 0 side-grasp, 1 top-grasp]) and Place (now parameterized by dx. dy, dz of pre-place location) Skills.
=> Added Object Specific Samplers for Grasp and Place Skills on Spot

predicators/ground_truth_models/spot/nsrts.py
Typo with range in grasp sampler for "low_wall_rack", and type of grasp.
=> Another Quick Fix for Grasp Sampler

mypy.ini, predicators/settings.py, predicators/spot_utils/spot_utils.py, setup.py
This PR adds Apriltag based object recognition inside the grasp skill. It will chose an image based grasp location at the center of the first fiducial it finds.
=> Added Apriltag Object Recognition

predicators/spot_utils/spot_utils.py
This PR keeps hand angle constant during grasp to post-grasp trajectory. It also fixes the place hand angle to be straight down.
=> Fixed Hand Angle During Grasping

predicators/envs/spot_env.py, predicators/ground_truth_models/spot/nsrts.py, predicators/spot_utils/spot_utils.py
This PR changes the place skill to use the obj that is passed into the skill and assumes it has an apriltag. Then it uses the fixed location of that apriltag to place relative to that object.
=> Fixed Place Skill for Bucket

predicators/spot_utils/spot_utils.py
Single line change fixing a typo that caused grasping other apriltag objects.
=> Fixed AprilTag Grasp Sampler

predicators/ground_truth_models/spot/nsrts.py, predicators/spot_utils/spot_utils.py
the reason for this change is that I wanted to be able to navigate to the extra room table (which wasn't in the original waypoint set), and when I tried to use the existing code, it just went to the low rack, and I was surprised
=> minor refactor of memorized waypoints

predicators/envs/spot_env.py, predicators/settings.py, predicators/spot_utils/spot_utils.py, scripts/spot_cube_table_repeat.sh
also a script for alternating between the two tables
=> spot env variation with just an april tag cube

predicators/approaches/active_sampler_learning_approach.py, predicators/explorers/active_sampler_explorer.py, predicators/ground_truth_models/spot/nsrts.py, predicators/main.py, predicators/ml_models.py, predicators/settings.py, predicators/utils.py, scripts/configs/active_sampler_learning.yaml, scripts/plotting/create_active_sampler_learning_plots.py, scripts/spot_cube_place_active_sampler_analysis.py, setup.py, tests/approaches/test_active_sampler_learning_approach.py
includes changes from https://github.com/Learning-and-Intelligent-Systems/predicators/pull/1490 that should be merged soon
=> aggressive sampler data saving

predicators/explorers/active_sampler_explorer.py, predicators/ground_truth_models/spot/nsrts.py, scripts/spot_cube_place_active_sampler_analysis.py
and some other bugs and improvements
=> fix bug in aggressive sampler data saving

predicators/ground_truth_models/spot/nsrts.py
oops, these important lines got lost (by me) during cleaning up of the large active learning PR!
=> fix place on floor

predicators/explorers/active_sampler_explorer.py
see https://github.com/Learning-and-Intelligent-Systems/predicators/pull/1500/files
I'm making this a separate PR because there are a few additional lines in the BDAI version of the code
=> fix bug in active sampler explorer

.gitignore, predicators/envs/spot_env.py, predicators/ground_truth_models/spot/nsrts.py, predicators/spot_utils/perception_utils.py, predicators/spot_utils/spot_utils.py
Changes necessary to make sure the robot is able to grasp while standing on the platform.
=> Grasp from atop platform

predicators/spot_utils/skills/spot_navigation.py
=> navigation skill refactor

predicators/spot_utils/perception/spot_cameras.py
new file for capturing images and extracting them from image responses, with standalone test
=> starting to refactor spot perception code

predicators/spot_utils/perception/object_detection.py, predicators/spot_utils/perception/perception_structs.py, predicators/spot_utils/perception/spot_cameras.py, predicators/spot_utils/skills/spot_grasp.py, predicators/spot_utils/skills/spot_stow_arm.py, predicators/spot_utils/utils.py
minor pull-out of code, not used
=> grasp skill refactor

predicators/spot_utils/integration_tests.py, predicators/spot_utils/utils.py, predicators/utils.py, tests/test_utils.py
=> integration test for sampling different offsets to move toward a table

predicators/envs/spot_env.py, predicators/ground_truth_models/spot/nsrts.py, predicators/ground_truth_models/spot/options.py, predicators/perception/spot_perceiver.py, predicators/utils.py
first PR described here https://docs.google.com/document/d/1GBW4-lzF5QY39G_ULi-P445O7eYHe7NVHl1NIAJweHQ/edit?pli=1
=> refactor spot cube environment in preparation for rearrangement env

predicators/envs/spot_env.py, predicators/ground_truth_models/spot/nsrts.py, predicators/ground_truth_models/spot/options.py, predicators/perception/spot_perceiver.py, predicators/spot_utils/graph_nav_maps/floor8-v2/metadata.yaml, predicators/spot_utils/utils.py
4th PR from here: https://docs.google.com/document/d/1GBW4-lzF5QY39G_ULi-P445O7eYHe7NVHl1NIAJweHQ/edit?pli=1
=> add container (bucket) to spot env

predicators/envs/spot_env.py, predicators/ground_truth_models/spot/nsrts.py, predicators/ground_truth_models/spot/options.py, predicators/perception/spot_perceiver.py, predicators/spot_utils/graph_nav_maps/floor8-v2/metadata.yaml, predicators/spot_utils/skills/spot_find_objects.py, predicators/spot_utils/utils.py, predicators/structs.py
5th PR described here: https://docs.google.com/document/d/1GBW4-lzF5QY39G_ULi-P445O7eYHe7NVHl1NIAJweHQ/edit?pli=1
=> add blocking predicates and chair environment

predicators/envs/spot_env.py, predicators/main.py
=> fix creation of spot perception debug utils if it doesn't exist

predicators/ground_truth_models/spot_env/options.py, predicators/spot_utils/integration_tests.py, predicators/spot_utils/perception/cv2_utils.py, predicators/spot_utils/perception/object_detection.py, predicators/spot_utils/perception/object_specific_grasp_selection.py, predicators/spot_utils/skills/spot_dump.py, predicators/spot_utils/skills/spot_grasp.py
also add integration test for grasping the platform handle
=> refactor grasp pixel selection and introduce cv2 utilities

predicators/envs/spot_env.py, predicators/spot_utils/graph_nav_maps/floor8-v2/metadata.yaml, tests/envs/test_spot_envs.py
also add genuine unit tests for dry run spot envs
=> add IsPlaceable predicate to prevent chair placing

predicators/ground_truth_models/spot_env/nsrts.py, predicators/ground_truth_models/spot_env/options.py, predicators/spot_utils/integration_tests.py, predicators/spot_utils/perception/object_detection.py, predicators/spot_utils/skills/spot_dump.py
Randomly select a pixel in the mask!
=> Actually sample a pixel for grasping

predicators/envs/spot_env.py, predicators/perception/spot_perceiver.py
1. change environment goal to be 'cup on table'
2. add HandEmpty as a precondition to MoveToHandView
=> two symbolic updates to real ball cup env

predicators/envs/spot_env.py, predicators/ground_truth_models/spot_env/options.py, predicators/utils.py
NOTE: also fixes bug related to name of 'dump' option and its interaction with the perceiver.
=> add precondition to prevent looking for held objects

predicators/utils.py, scripts/spot_pick_sampler_analysis.py, tests/test_utils.py
also merge in upstream changes.
example outputs:
https://github.com/bdaiinstitute/predicators/assets/135051706/32144da3-6c79-4fad-b8f8-c00d0e90da60
https://github.com/bdaiinstitute/predicators/assets/135051706/fa260879-44f6-4d0a-8b01-149f2ef220ca
https://github.com/bdaiinstitute/predicators/assets/135051706/28d19226-4592-44ba-bdb3-ebd457f1d4e0
https://github.com/bdaiinstitute/predicators/assets/135051706/95f6328e-2d95-4169-a919-a9ecb4b60f59
=> add analysis script for spot sim pick sampler learning

predicators/ground_truth_models/spot_env/nsrts.py, predicators/perception/spot_perceiver.py, predicators/spot_utils/perception/object_detection.py, predicators/spot_utils/skills/spot_place.py, predicators/utils.py
Fix place sampler, also put `plt.close()` statements in a bunch of places to free up memory/enable garbage collection (I strongly suspect not doing `plt.close()` is why our program has been consuming a crazy amount of memory when we visualize things)
=> fix placing

predicators/ground_truth_models/spot_env/nsrts.py, predicators/ground_truth_models/spot_env/options.py, predicators/utils.py, tests/envs/test_spot_envs.py
and add unit test for real robo
=> fix place sampler

predicators/ground_truth_models/spot_env/options.py, predicators/spot_utils/learned_sampler_visualizations.py, scripts/configs/spot_active_sampler_learning.yaml
=> Minor Fixes

predicators/spot_utils/perception/object_detection.py
sometimes the best-scoring segmentation leads to pose detection failures due to depth issues. before we would just fail, even if some other camera with better depth reading also saw the object. now we'll fall back to that other camera. (I saw this happen in practice)
=> small improvement to sam/detic detection pipeline

predicators/envs/spot_env.py, predicators/ground_truth_models/spot_env/nsrts.py, predicators/ground_truth_models/spot_env/options.py, predicators/spot_utils/skills/spot_sweep.py, predicators/utils.py, tests/envs/test_spot_envs.py
also add real robot test to visualize base sampler
=> parameterize sweeping by velocity

predicators/envs/spot_env.py
move to hand view failures are nothing but trouble, so I propose this hack
=> move to hand view object hack

predicators/spot_utils/utils.py, tests/envs/test_spot_envs.py
also updates real robot test to verify the change
=> place held objects (like the brush) lower on the floor

predicators/envs/spot_env.py, predicators/spot_utils/graph_nav_maps/floor8-sweeping/metadata.yaml, scripts/configs/active_sampler_learning.yaml, tests/envs/test_spot_envs.py
=> fix dry task generation for sweeping map

predicators/envs/spot_env.py, predicators/ground_truth_models/spot_env/nsrts.py, predicators/perception/spot_perceiver.py, predicators/spot_utils/graph_nav_maps/floor8-sweeping/metadata.yaml, predicators/spot_utils/graph_nav_maps/floor8-v2/metadata.yaml, predicators/spot_utils/perception/object_detection.py, predicators/spot_utils/perception/object_specific_grasp_selection.py, predicators/spot_utils/skills/spot_find_objects.py, predicators/spot_utils/utils.py, tests/envs/test_spot_envs.py
also fix metadata for table that was leading to too-high placing on the table
=> chips -> small toy football

predicators/envs/spot_env.py, predicators/ground_truth_models/spot_env/nsrts.py, predicators/spot_utils/perception/object_specific_grasp_selection.py
Fixes to the perception of the yogurt, and feature to enable human to take over when the robot is unable to view an object after moving. Also modifies the base sampler for sweeping
=> Perception + navigation fixes

predicators/envs/spot_env.py, predicators/ground_truth_models/spot_env/nsrts.py, predicators/settings.py, predicators/spot_utils/graph_nav_maps/floor8-sweeping/metadata.yaml, predicators/spot_utils/perception/object_specific_grasp_selection.py, predicators/spot_utils/skills/spot_grasp.py, predicators/spot_utils/skills/spot_sweep.py
Modifies objects, creates new object-specific grasp for new chair
=> Add new objects to map

predicators/envs/spot_env.py, predicators/ground_truth_models/spot_env/options.py, predicators/spot_utils/graph_nav_maps/floor8-sweeping/metadata.yaml, predicators/spot_utils/perception/object_specific_grasp_selection.py, predicators/spot_utils/skills/spot_sweep.py
Notable changes:
- Swapped out football for basketball
- More prompt hacking
- Modified the `inside` threshold classifier to prevent misfires
=> Lots of fixes!

predicators/envs/spot_env.py, predicators/ground_truth_models/spot_env/nsrts.py, predicators/ground_truth_models/spot_env/options.py, predicators/spot_utils/graph_nav_maps/floor8-sweeping/metadata.yaml, predicators/spot_utils/skills/spot_sweep.py
Sweeping was failing frequently due to minor errors in localization/object height estimation. This introduces a slew of changes to try to be more robust to that.
=> Changes sweeping to be more robust
